# Generated by Django 5.1.1 on 2024-09-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_chaivariety_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='discount',
            field=models.TextField(default=0, max_length=3),
        ),
    ]
