# Generated by Django 5.0.7 on 2024-08-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
    ]
